"""add token blacklist

Revision ID: 93753a466f05
Revises: 351d631c018b
Create Date: 2026-03-19 16:51:04.019372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93753a466f05'
down_revision = '351d631c018b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom_members', schema=None) as batch_op:
        batch_op.alter_column('is_creator',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom_members', schema=None) as batch_op:
        batch_op.alter_column('is_creator',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
